name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: true
          check_name: "${linter}"
          # Enable linters
          prettier: true
          eslint: true


# name: ESLint

# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     # - name: Get file changes
#     #   id: get_file_changes
#     #   uses: trilom/file-changes-action@v1.2.3
#     #   with:
#     #     output: ' '
#     # - name: Echo file changes
#     #   run: |
#     #     echo Changed files: ${{ steps.get_file_changes.outputs.files }}
#     # - uses: actions/checkout@v2
#     # - name: Install modules
#     #   run: yarn
#     # - name: Run ESLint
#     #   run: npx eslint ${{ steps.get_file_changes.outputs.files }}
#     - uses: actions/checkout@v2
#     - name: Install modules
#       run: yarn
#     - name: Run ESLint
#       run: npx eslint . --fix



#     # - uses: actions/checkout@v2
#     # - name: Install modules
#     #   run: yarn
#     # - name: Run ESLint
#     #   run: eslint . --ext .js,.jsx,.ts,.tsx
