name: ESLint

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check for ESLint errors
    uses: getsentry/action-eslint-fix@v1
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      dry: true
