name: Jest CI

on: [push]

jobs:
  build:

    runs-on: docker://alpine:3.8

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn test
      env:
        CI: true
